/*
================================================================================
File Name : GUI_Config.H
Author    : LiYOng
Date      : 2008-12-12 15:51
Version   : 1.0
Decription: This file offers some options to reduce ROM size and some GUI configs
================================================================================
*/
#ifndef _GUI_CONFIG_H_
#define _GUI_CONFIG_H_

/*
================================================================================
COnfigurations and options
================================================================================
*/
/*LCD size*/
#define  GUI_LCM_XMAX  127
#define  GUI_LCM_YMAX  129

/*Color information*/
#define  TCOLOR  INT16U  //Color information, How many bits ?


#endif//_GUI_CONFIG_H_
/*
================================================================================
====================================End of file=================================
================================================================================
*/

